#define SHIP_CONTROL 1
#define SHIP_WEAPONS 2
#define SHIP_SHIELDS 4
#define SHIP_REPAIR 8
#define SHIP_ENGINES 16

#define STARTING_FACTION_CASH 45000
#define STARTING_FACTION_WARSHIPS 25
#define STARTING_FACTION_MERCHANTS 10
